# Generated by Django 4.2.5 on 2023-10-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscriber_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
